#!/bin/bash
# Oz sandbox profile setup for Dapper Linux
# Typically Oz requires executables to be "diverted"/moved to /usr/bin-oz 
# and symlinks pointing back to /usr/bin/oz left in place.
# Dapper Linux takes a different approach and leaves the executables in place,
# which enables execuables to be updated and have pax flags set.
# So instead, we use the "oz launch <profile>" command, and stick it in 
# application .desktop files, which is less intrusive.

#------------------------------
# Document and Image viewing
#------------------------------
# Eog
if [ -e /usr/share/applications/eog.desktop ]
then
    sed -i "s/Exec=eog %U/Exec=oz launch eog %U/g" /usr/share/applications/eog.desktop
fi
# Evince
if [ -e /usr/share/applications/evince.desktop ]
then
    sed -i "s/Exec=evince %U/Exec=oz launch evince %U/g" /usr/share/applications/evince.desktop
fi

#------------------------------
# Image Editing
#------------------------------
#Gimp
if [ -e /usr/share/applications/gimp.desktop ]
then
    sed -i "s/Exec=gimp-2.8 %U/Exec=oz launch gimp %U/g" /usr/share/applications/gimp.desktop
fi
# Krita
if [ -e /usr/share/applications/org.kde.krita.desktop ]
then
    sed -i "s/Exec=krita %U/Exec=oz launch krita %U/g" /usr/share/applications/org.kde.krita.desktop
fi
# Inkscape
if [ -e /usr/share/applications/inkscape.desktop ]
then
    sed -i "s/Exec=inkscape %F/Exec=oz launch inkscape %F/g" /usr/share/applications/inkscape.desktop
fi

#------------------------------
# Misc Applications
#------------------------------
# Builder
if [ -e /usr/share/applications/org.gnome.Builder.desktop ]
then
    sed -i "s/Exec=gnome-builder %U/Exec=oz launch gnome-builder %U/g" /usr/share/applications/org.gnome.Builder.desktop
    sed -i "s/DBusActivatable=true/DBusActivatable=false/g" /usr/share/applications/org.gnome.Builder.desktop
fi
# Gedit
if [ -e /usr/share/applications/org.gnome.gedit.desktop ]
then
    sed -i "s/Exec=gedit/Exec=oz launch gedit/g" /usr/share/applications/org.gnome.gedit.desktop
    sed -i "s/DBusActivatable=true/DBusActivatable=false/g" /usr/share/applications/org.gnome.gedit.desktop
fi
# Pdfshuffler
if [ -e /usr/share/applications/pdfshuffler.desktop ]
then
    sed -i "s/Exec=pdfshuffler/Exec=oz launch pdfshuffler/g" /usr/share/applications/pdfshuffler.desktop
fi
# Nautilus
if [ -e /usr/share/applications/org.gnome.Nautilus.desktop ]
then
    sed -i "s/Exec=nautilus/Exec=oz launch nautilus/g" /usr/share/applications/org.gnome.Nautilus.desktop
    sed -i "s/DBusActivatable=true/DBusActivatable=false/g" /usr/share/applications/org.gnome.Nautilus.desktop
fi

#------------------------------
# Media Programs
#------------------------------
# Gnome-music
if [ -e /usr/share/applications/gnome-music.desktop ]
then
    sed -i "s/Exec=gnome-music/Exec=oz launch gnome-music/g" /usr/share/applications/gnome-music.desktop
fi
# Spotify
if [ -e /usr/share/applications/spotify.desktop ]
then
    sed -i "s/Exec=spotify %U/Exec=oz launch spotify/g" /usr/share/applications/spotify.desktop
fi
# Totem
if [ -e /usr/share/applications/org.gnome.Totem.desktop ]
then
    sed -i "s/Exec=totem %U/Exec=oz launch totem %U/g" /usr/share/applications/org.gnome.Totem.desktop
    sed -i "s/DBusActivatable=true/DBusActivatable=false/g" /usr/share/applications/org.gnome.Totem.desktop
fi
# VLC
if [ -e /usr/share/applications/vlc.desktop ]
then
    sed -i "s#Exec=/usr/bin/vlc --started-from-file %U#Exec=oz launch vlc %U#g" /usr/share/applications/vlc.desktop
fi

#------------------------------
# Document Editing
#------------------------------
#Lyx
if [ -e /usr/share/applications/lyx.desktop ]
then
    sed -i "s/Exec=lyx %F/Exec=oz launch lyx %F/g" /usr/share/applications/lyx.desktop
fi
# Libreoffice
if [ -e /usr/share/applications/libreoffice-startcenter.desktop ]
then
    sed -i "s/Exec=libreoffice %U/Exec=oz launch libreoffice %U/g" /usr/share/applications/libreoffice-startcenter.desktop
fi
# Libreoffice Writer
if [ -e /usr/share/applications/libreoffice-writer.desktop ]
then
    sed -i "s/Exec=libreoffice --writer %U/Exec=oz launch libreoffice-writer %U/g" /usr/share/applications/libreoffice-writer.desktop
fi
# Libreoffice Impress
if [ -e /usr/share/applications/libreoffice-impress.desktop ]
then
    sed -i "s/Exec=libreoffice --impress %U/Exec=oz launch libreoffice-impress %U/g" /usr/share/applications/libreoffice-impress.desktop
fi
# Libreoffice Calc
if [ -e /usr/share/applications/libreoffice-calc.desktop ]
then
    sed -i "s/Exec=libreoffice --calc %U/Exec=oz launch libreoffice-calc %U/g" /usr/share/applications/libreoffice-calc.desktop
fi
# Libreoffice Draw
if [ -e /usr/share/applications/libreoffice-draw.desktop ]
then
    sed -i "s/Exec=libreoffice --draw %U/Exec=oz launch libreoffice-draw %U/g" /usr/share/applications/libreoffice-draw.desktop
fi
# Scribus
if [ -e /usr/share/applications/scribus.desktop ]
then
    sed -i "s/Exec=scribus %f/Exec=oz launch scribus %f/g" /usr/share/applications/scribus.desktop
fi

#------------------------------
# Web Browsers and Email
#------------------------------
# Firefox
if [ -e /usr/share/applications/firefox.desktop ]
then
    sed -i "s/Exec=firefox %u/Exec=oz launch firefox %u/g" /usr/share/applications/firefox.desktop
    sed -i "s/Exec=firefox --private-window %u/Exec=oz launch firefox-private %u/g" /usr/share/applications/firefox.desktop
fi
# Dapper Hardened Browser
if [ -e /usr/share/applications/dapper-hardened-browser.desktop ]
then
    sed -i "s/Exec=dapper-hardened-browser %u/Exec=oz launch dapper-hardened-browser %u/g" /usr/share/applications/dapper-hardened-browser.desktop
fi
# Thunderbird
if [ -e /usr/share/applications/mozilla-thunderbird.desktop ]
then
    sed -i "s/Exec=thunderbird %u/Exec=oz launch thunderbird %u/g" /usr/share/applications/mozilla-thunderbird.desktop
fi
# Evolution
if [ -e /usr/share/applications/evolution.desktop ]
then
    sed -i "s/Exec=evolution/Exec=oz launch evolution/g" /usr/share/applications/evolution.desktop
fi

#------------------------------
# Internet enabled programs
#------------------------------
# Liferea
if [ -e /usr/share/applications/liferea.desktop ]
then
    sed -i "s/Exec=liferea/Exec=oz launch liferea/g" /usr/share/applications/liferea.desktop
fi
# Polari
if [ -e /usr/share/applications/org.gnome.Polari.desktop ]
then
    sed -i "s/Exec=gapplication launch org.gnome.Polari/Exec=oz launch polari/g" /usr/share/applications/org.gnome.Polari.desktop
    sed -i "s/DBusActivatable=true/DBusActivatable=false/g" /usr/share/applications/org.gnome.Polari.desktop
fi
# Transmission
if [ -e /usr/share/applications/transmission-gtk.desktop ]
then
    sed -i "s/Exec=transmission-gtk/Exec=oz launch transmission/g" /usr/share/applications/transmission-gtk.desktop
fi
